version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint-django
    versions:
    - 2.4.2
    - 2.4.3
  - dependency-name: asgiref
    versions:
    - 3.3.1
    - 3.3.2
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: django-crispy-forms
    versions:
    - 1.10.0
    - 1.11.0
    - 1.11.1
  - dependency-name: autopep8
    versions:
    - 1.5.4
    - 1.5.5
  - dependency-name: django-debug-toolbar
    versions:
    - "3.2"
  - dependency-name: django
    versions:
    - 3.0.7
