# Generated by Django 3.0.2 on 2020-02-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'name'], name='blog_produc_name_6cba00_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['description'], name='description1'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='price1'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['quantity'], name='quantity'),
        ),
         migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['farmer_id'], name='farmer_id1'),
        ),
         migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['productCate_id'], name='productCate_id1'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['image'], name='image1'),
        ),
    ]
